apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cpt-api
  name: cpt-svc-np
  namespace: cpt-api
spec:
  ports:
    - name: 5000-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: cpt-api
  type: NodePort
status:
  loadBalancer: {}